// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hczdbhxsgztmfmqkcqki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjemRiaHhzZ3p0bWZtcWtjcWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTM5MjUsImV4cCI6MjA3ODE4OTkyNX0.55SpaD1KWtfPYBBvVCHMgzRNDvxABlD0EAUlfOp2h-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});